[package]
name = "parquet2json"
description = "A command-line tool for converting Parquet to newline-delimited JSON"
version = "1.0.1"
edition = "2018"
license = "MIT"
authors = ["Pieter Raubenheimer <pieter@wavana.com>", "rdettai <contact@cloudfuse.io>"]
repository = "https://github.com/jupiter/parquet2json"

[dependencies]
arrow = { version = "4.3", features = ["prettyprint"] }
async-trait = "0.1"
clap = "3.0.0-beta.2"
parquet = { version = "4.4", features = ["arrow", "cli"] }
regex = { version = "1.5.4" }
rusoto_core = { version = "0.47.0", default_features = false, features=["rustls"] }
rusoto_s3 = { version = "0.47.0", default_features = false, features=["rustls"] }
tokio = { version = "1.0", features = ["fs", "macros", "io-std"] }
url = { version = "2.2.2" }
