[package]
name = "parquet2json"
description = "A command-line tool for converting Parquet to newline-delimited JSON"
version = "1.2.3"
edition = "2018"
license = "MIT"
authors = ["Pieter Raubenheimer <pieter@wavana.com>"]
repository = "https://github.com/jupiter/parquet2json"

[dependencies]
bytes = { version = "1.0.1" }
chunked-bytes = { version = "0.3.0" }
crossbeam-channel = { version = "0.5.1" }
clap = "2.34.0"
lazy_static = { version = "1.4.0" }
openssl = { version = "0.10", features = ["vendored"] }
parquet = { version = "6.5.0", features = ["cli"] }
regex = { version = "1.5.4" }
reqwest = { version = "0.11", features = ["blocking"] }
rusoto_core = { version = "0.47.0", default_features = false, features=["rustls"] }
rusoto_s3 = { version = "0.47.0", default_features = false, features=["rustls"] }
tokio = { version = "1.0" }
tokio-stream = { version = "0.1.7" }
url = { version = "2.2.2" }
