[package]
name = "parquet2json"
description = "A command-line tool for converting Parquet to newline-delimited JSON"
version = "1.0.0"
edition = "2018"
license = "Apache-2.0"
authors = ["Pieter Raubenheimer <pieter@wavana.com>"]
repository = "https://github.com/jupiter/parquet2json"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
parquet = { version = "4.4.0", features = ["cli"] }
