name: Merge
on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test
      - name: Lint
        run: cargo clippy --all-targets -- -D warnings
      - name: Format
        run: cargo fmt -- --check
